import { useQuery } from "@tanstack/react-query";
import { api, isAssessmentDetail, type Assessment } from "../../shared/api/client";
import { AsyncState } from "../../shared/ui/AsyncState";
import { AssessmentSummary } from "./AssessmentSummary";
const object=(value:unknown):value is Record<string,unknown>=>typeof value==='object'&&value!==null&&!Array.isArray(value);
export function ModelEvidence({assessment,componentId}:{assessment:Assessment|null;componentId:string}){
  const query=useQuery({queryKey:['assessment-evidence',assessment?.id],queryFn:()=>api(`/assessments/${encodeURIComponent(assessment!.id)}`,undefined,isAssessmentDetail),enabled:!!assessment});
  const data=query.data,aligned=data?.id===assessment?.id&&data?.component_id===componentId&&data?.input_version===assessment?.input_version&&data?.model_version===assessment?.model_version;
  const explanation=data?.evidence?.explanation,calibration=data?.evidence?.calibration;
  const level=object(calibration)&&typeof calibration.nominal_coverage==='number'&&calibration.nominal_coverage>0&&calibration.nominal_coverage<1?calibration.nominal_coverage:undefined;
  const contributions=object(explanation)&&Array.isArray(explanation.contributions)?explanation.contributions.filter((item):item is {feature:string;difference_cycles:number}=>object(item)&&typeof item.feature==='string'&&typeof item.difference_cycles==='number'&&Number.isFinite(item.difference_cycles)):[];
  return <article className="card model-evidence"><h2>Assessment & model evidence</h2><AsyncState loading={query.isLoading} error={query.error} empty={!assessment} emptyMessage="No assessment evidence is available" onRetry={()=>void query.refetch()}>{data&&(aligned?<><AssessmentSummary assessment={assessment} level={level}/><p className="footnote">History through cycle {data.cutoff_cycle??'not recorded'} · Model {data.model_version??'unavailable'} · Input {data.input_version}</p><h3>Model influence</h3>{data.explanation.state==='available'&&object(explanation)&&contributions.length?<><p>{typeof explanation.reference==='string'?explanation.reference:'Reference not supplied'}</p><div className="table-scroll"><table><caption className="sr-only">Model-input sensitivities in cycles</caption><thead><tr><th>Model input</th><th>Difference (cycles)</th></tr></thead><tbody>{contributions.slice(0,10).map(item=><tr key={item.feature}><td>{item.feature}</td><td>{item.difference_cycles.toFixed(2)}</td></tr>)}</tbody></table></div><p className="footnote">{typeof explanation.limitations==='string'?explanation.limitations:'Model influences are not confirmed physical fault causes.'}</p><p className="footnote">Method: {typeof explanation.method==='string'?explanation.method:'Not supplied'} · Version: {typeof explanation.version==='string'?explanation.version:'Not supplied'}</p></>:<p className="quality-finding">{data.explanation.reason} No physical fault cause is inferred.</p>}</>:<p role="alert">Evidence does not match the selected component/input version. Refresh the record before use.</p>)}</AsyncState></article>;
}
