import * as Dialog from "@radix-ui/react-dialog";
import type { Plan } from "../../shared/api/client";
import { useSession } from "../access/SessionGate";
import { Icon } from "../../shared/ui/Icon";
export function PlanApproval({ plan, pending, onApprove }: { plan: Plan; pending: boolean; onApprove: (id: string) => void }) {
  const session=useSession();
  const allowed=session?.role==='supervisor';
  const usable=['optimal','feasible'].includes(plan.solver_status);
  if (plan.status !== "proposed") return <div className="approval-state"><Icon name={plan.status === "approved" ? "check" : "file"} size={20}/><div><strong>{plan.status === "approved" ? "Plan approved" : "Approval unavailable"}</strong><p>{plan.approved_by ? `Committed by ${plan.approved_by}${plan.approved_at ? ` · ${new Date(plan.approved_at).toLocaleString()}` : ""}` : `This proposal has a ${plan.solver_status} solver outcome.`}</p></div></div>;
  return <div className="approval-console"><div><strong>{usable?"Ready for human review":"No approvable schedule"}</strong><p>{!usable?"A feasible or optimal result is required before approval.":!allowed?"Supervisor permission is required to approve this exact proposal.":"Approval rechecks current inputs and commits required parts. A proposal reserves nothing."}</p></div><Dialog.Root><Dialog.Trigger asChild><button disabled={pending||!allowed||!usable}><Icon name="check" size={17}/>{pending ? "Committing…" : "Review & approve"}</button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog-content"><div className="dialog-heading"><span className="dialog-icon"><Icon name="calendar" size={22}/></span><Dialog.Close asChild><button className="icon-button" aria-label="Close approval review"><Icon name="close" size={19}/></button></Dialog.Close></div><Dialog.Title>Approve this maintenance plan?</Dialog.Title><Dialog.Description>Review this exact proposal. The server will recheck tasks, stock and input versions before committing reservations.</Dialog.Description><dl className="record-details"><div><dt>Proposal</dt><dd className="mono">{plan.id}</dd></div><div><dt>Scheduled tasks</dt><dd>{plan.assignments.length}</dd></div><div><dt>Input snapshot</dt><dd className="mono">{plan.input_version}</dd></div><div><dt>Solver outcome</dt><dd>{plan.solver_status}</dd></div></dl><p className="footnote">This records a demonstration maintenance decision. It does not provide aircraft clearance.</p><div className="dialog-actions"><Dialog.Close asChild><button className="secondary">Keep reviewing</button></Dialog.Close><Dialog.Close asChild><button onClick={() => onApprove(plan.id)} disabled={pending||!allowed||!usable}><Icon name="check" size={16}/>Approve & reserve parts</button></Dialog.Close></div></Dialog.Content></Dialog.Portal></Dialog.Root></div>;
}
