import {useQuery} from '@tanstack/react-query';
import {api,isPlanCommitment,type Plan} from '../../shared/api/client';
import {AsyncState} from '../../shared/ui/AsyncState';
import {StatusBadge} from '../../shared/ui/StatusBadge';
export function PlanHistory({plan}:{plan:Plan}){
 const query=useQuery({queryKey:['plan-commitment',plan.id],queryFn:()=>api(`/plans/${encodeURIComponent(plan.id)}/commitment`,undefined,isPlanCommitment),enabled:plan.status!=='proposed'});
 const history=query.data;
 return <article className="card commitment-history"><div className="card-heading"><div><h2>Reservations & work history</h2><p>Retained records for this exact proposal. A proposal reserves nothing.</p></div></div>{plan.status==='proposed'?<p className="history-empty">This proposal has not committed stock or work records.</p>:<AsyncState loading={query.isLoading} error={query.error} onRetry={()=>void query.refetch()}>{history&&(history.plan_id===plan.id?<><div className="table-scroll"><table><caption>Part commitment records</caption><thead><tr><th>Reservation</th><th>Part</th><th>Quantity (units)</th><th>Status</th></tr></thead><tbody>{history.reservations.map(row=><tr key={row.id}><td>{row.id}</td><td>{row.part_id}</td><td>{row.quantity}</td><td><StatusBadge status={row.status}/></td></tr>)}</tbody></table></div>{!history.reservations.length&&<p className="history-empty">No retained reservation rows for this plan.</p>}<div className="table-scroll"><table><caption>Work records</caption><thead><tr><th>Task / work</th><th>Status</th><th>Consumed (units)</th><th>Recorded outcome</th></tr></thead><tbody>{history.work.map(row=><tr key={row.id}><td>{row.task_id}<small className="table-subtitle mono">{row.id} · v{row.version}</small></td><td><StatusBadge status={row.status}/></td><td>{row.consumed_quantity}</td><td>{row.notes||'No outcome notes'}<small className="table-subtitle">{row.completed_at?`Completed ${new Date(row.completed_at).toLocaleString()}`:row.started_at?`Started ${new Date(row.started_at).toLocaleString()}`:'No start or completion time recorded'}</small></td></tr>)}</tbody></table></div>{!history.work.length&&<p className="history-empty">No retained work rows for this plan.</p>}</>:<p role="alert">Commitment history does not match this proposal.</p>)}</AsyncState>}</article>;
}
