import { useState } from "react";
import { semanticColor } from "../../shared/styles/semanticColor";
import { Chart } from "../../shared/charts/Chart";
import type { Scenario, SimulationRun } from "../../shared/api/client";
import { AsyncState } from "../../shared/ui/AsyncState";
export function ScenarioComparison({ runs, scenarios, loading, error, onRetry }: { runs?:SimulationRun[]; scenarios?:Scenario[]; loading:boolean; error:Error|null; onRetry?:()=>void }) {
  const [baselineId,setBaselineId]=useState(''),[alternativeId,setAlternativeId]=useState('');
  const baseline=runs?.find(run=>run.id===baselineId)??runs?.[0],alternative=runs?.find(run=>run.id===alternativeId)??runs?.[1];
  const context=(run:SimulationRun|undefined)=>{const value=run?.metrics.assumptions;return typeof value==='object'&&value!==null&&!Array.isArray(value)?value as Record<string,unknown>:undefined;};
  const baseContext=context(baseline),altContext=context(alternative);
  const supported=(value:Record<string,unknown>|undefined)=>!!value&&typeof value.horizon_hours==='number'&&value.horizon_hours>0&&typeof value.aircraft_count==='number'&&Number.isInteger(value.aircraft_count)&&value.aircraft_count>0&&Array.isArray(value.maintenance_events)&&value.maintenance_events.every(event=>Array.isArray(event)&&event.length===2&&event.every(number=>typeof number==='number'&&Number.isFinite(number)));
  const comparable=supported(baseContext)&&supported(altContext)&&!!baseline&&!!alternative&&baseline.id!==alternative.id&&baseContext?.horizon_hours===altContext?.horizon_hours&&typeof baseContext?.horizon_hours==='number'&&baseContext?.aircraft_count===altContext?.aircraft_count&&JSON.stringify(baseContext?.maintenance_events)===JSON.stringify(altContext?.maintenance_events);
  const comparison=<div className="scenario-comparison"><div className="comparison-selectors"><div><label htmlFor="baseline-run">Baseline run</label><select id="baseline-run" value={baseline?.id??''} onChange={event=>setBaselineId(event.target.value)}>{runs?.map(run=><option key={run.id} value={run.id}>{run.id}</option>)}</select></div><div><label htmlFor="alternative-run">Alternative run</label><select id="alternative-run" value={alternative?.id??''} onChange={event=>setAlternativeId(event.target.value)}>{runs?.map(run=><option key={run.id} value={run.id}>{run.id}</option>)}</select></div></div>{comparable?<><Chart label="Baseline and alternative simulated aircraft-time availability in percent" option={{tooltip:{trigger:'axis'},grid:{left:75,right:24,top:20,bottom:35},xAxis:{type:'value',min:0,max:100,name:'Percent'},yAxis:{type:'category',data:['Baseline','Alternative']},series:[{type:'bar',data:[baseline!.availability*100,alternative!.availability*100],itemStyle:{color:semanticColor('accent')},barWidth:26,label:{show:true,position:'right',formatter:'{c}%'}}]}}/><p className="footnote">Simulated aircraft-time availability over {String(baseContext?.horizon_hours)} hours · {String(baseContext?.aircraft_count)} aircraft. Difference: {((alternative!.availability-baseline!.availability)*100).toFixed(1)} percentage points. One deterministic run per revision; no replication uncertainty is inferred.</p></>:<p className="quality-finding">Select two saved runs with matching horizon, fleet count and maintenance demand. Comparable retained assumptions are required; different or unavailable contexts cannot imply improvement.</p>}</div>;
  const names = new Map(scenarios?.map((scenario) => [scenario.id,scenario.name]));
  return <article className="card"><div className="card-heading"><div><h2>Simulation results</h2><p>One deterministic run has no inferred uncertainty interval.</p></div><span className="source-tag">Simulated projections</span></div><AsyncState loading={loading} error={error} empty={!runs?.length} emptyMessage="Run a scenario to see its projected outcome" onRetry={onRetry}>{comparison}<div className="table-scroll"><table><caption className="sr-only">Recorded simulation runs</caption><thead><tr><th scope="col">Scenario / run</th><th scope="col">Aircraft-time availability</th><th scope="col">Downtime</th><th scope="col">Queue wait</th><th scope="col">Part wait</th><th scope="col">Seed</th></tr></thead><tbody>{runs?.map((result) => <tr key={result.id}><td><strong>{names.get(result.scenario_id) ?? result.scenario_id}</strong><small className="table-subtitle mono">{result.id}</small></td><td><div className="availability-cell"><strong>{(result.availability*100).toFixed(1)}%</strong><div className="availability-track"><i style={{ width:`${result.availability*100}%` }}/></div></div></td><td>{typeof result.metrics.downtime_aircraft_hours === "number" ? `${result.metrics.downtime_aircraft_hours} aircraft-hours` : "Not recorded"}</td><td>{typeof result.metrics.queue_wait_hours === "number" ? `${result.metrics.queue_wait_hours} hours` : "Not recorded"}</td><td>{typeof result.metrics.part_wait_hours === "number" ? `${result.metrics.part_wait_hours} hours` : "Not recorded"}</td><td className="mono">{result.seed}</td></tr>)}</tbody></table></div><div className="table-footer"><span>{runs?.length} recorded runs</span><span>Scenario-specific synthetic projections</span></div></AsyncState></article>;
}
