import { useState, type FormEvent } from "react";
import type { Scenario } from "../../shared/api/client";
import { useSession } from "../access/SessionGate";
import { Icon } from "../../shared/ui/Icon";
export type ScenarioRevisionInput={name:string;expected_version:number;horizon_hours:number;aircraft_count:number;maintenance_capacity:number;maintenance_events:number[][];part_available_hours:number};
export function ScenarioEditor({scenario,pending,submitting,onRun,onRevise,revisionPending}:{scenario:Scenario;pending:boolean;submitting?:boolean;onRun:(id:string)=>void;onRevise:(id:string,input:ScenarioRevisionInput)=>void;revisionPending:boolean}){
  const session=useSession();const allowed=['planner','supervisor'].includes(session?.role??'');
  const [editing,setEditing]=useState(false),[name,setName]=useState(`${scenario.name} · alternative`),[part,setPart]=useState(String(scenario.assumptions.part_available_hours??0)),[capacity,setCapacity]=useState(String(scenario.assumptions.maintenance_capacity??1)),[error,setError]=useState('');
  const fields=[{label:'Aircraft',value:scenario.assumptions.aircraft_count,unit:'records'},{label:'Maintenance capacity',value:scenario.assumptions.maintenance_capacity,unit:'concurrent events'},{label:'Simulation horizon',value:scenario.assumptions.horizon_hours,unit:'hours'},{label:'Parts available at',value:scenario.assumptions.part_available_hours??0,unit:'hours after start'}];
  function revise(event:FormEvent){event.preventDefault();setError('');const horizon=scenario.assumptions.horizon_hours,count=scenario.assumptions.aircraft_count,events=scenario.assumptions.maintenance_events;const partHours=Number(part),crew=Number(capacity);if(typeof horizon!=='number'||typeof count!=='number'||!Array.isArray(events)||!events.every(item=>Array.isArray(item)&&item.length===2&&item.every(value=>typeof value==='number'&&Number.isFinite(value)))){setError('This scenario has no supported event definition for revision.');return;}if(!Number.isFinite(partHours)||partHours<0||partHours>=horizon||!Number.isInteger(crew)||crew<1){setError('Use a part availability time inside the horizon and a positive whole-number capacity.');return;}onRevise(scenario.id,{name,expected_version:scenario.version,horizon_hours:horizon,aircraft_count:count,maintenance_capacity:crew,maintenance_events:events as number[][],part_available_hours:partHours});}
  return <article className="card scenario-card" data-scenario-id={scenario.id}><div className="scenario-card-top"><span className="scenario-icon"><Icon name="chart" size={22}/></span><span className="source-tag">Revision {scenario.version}</span></div><h3>{scenario.name}</h3><p>Saved synthetic scenario. A revision creates a new record; live inventory is unchanged.</p><dl className="scenario-facts">{fields.map(field=><div key={field.label}><dt>{field.label}</dt><dd>{typeof field.value==='number'?field.value:'Unspecified'}<small>{field.unit}</small></dd></div>)}</dl><details className="technical-details"><summary>Inspect full assumptions</summary><pre>{JSON.stringify(scenario.assumptions,null,2)}</pre><p className="mono muted">{scenario.id} · {scenario.provenance}</p></details><div className="scenario-actions"><button onClick={()=>onRun(scenario.id)} disabled={pending||!allowed}><Icon name="chart" size={16}/>{submitting?'Submitting simulation…':'Run simulation'}</button><button className="button-secondary" onClick={()=>setEditing(value=>!value)} disabled={!allowed} aria-expanded={editing}>Revise assumptions</button></div>{!allowed&&<p className="footnote">Planner or supervisor permission is required.</p>}{editing&&<form className="scenario-revision" onSubmit={revise}><label>Alternative name<input required maxLength={120} value={name} onChange={event=>setName(event.target.value)}/></label><label>Part availability (hours)<input type="number" required min={0} step="0.5" value={part} onChange={event=>setPart(event.target.value)}/></label><label>Maintenance capacity<input type="number" required min={1} step={1} value={capacity} onChange={event=>setCapacity(event.target.value)}/></label><p className="footnote">Research assumption: all events wait for a shared part-availability time before requesting maintenance capacity. No spare demand or physical stock is inferred.</p>{error&&<p role="alert">{error}</p>}<button disabled={revisionPending}>{revisionPending?'Saving revision…':'Save new revision'}</button></form>}</article>;
}
