import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";

import { api, arrayOf, isInventoryPart, type InventoryPart } from "../../shared/api/client";
import { AsyncState } from "../../shared/ui/AsyncState";
import { PartsBottlenecks } from "./PartsBottlenecks";

export function InventoryPage() {
  const query = useQuery({ queryKey: ["inventory"], queryFn: () => api<InventoryPart[]>("/inventory", undefined, arrayOf(isInventoryPart)) });
  return <section><div className="page-title"><div><span className="eyebrow">Inventory</span><h1>Parts for upcoming work</h1><p>Available stock equals on-hand stock minus committed reservations. A shortage remains visible until a new record changes it.</p></div><Link className="button ghost-light" to="/planning">Return to planning →</Link></div>{query.data&&<PartsBottlenecks parts={query.data}/>}<AsyncState loading={query.isLoading} error={query.error} empty={!query.data?.length}><div className="parts-grid">{query.data?.map((part,index) => {const available=part.on_hand-part.reserved;const constrained=available===0;return <article className={`part-card ${constrained?"part-critical":""}`} key={part.id}><div className="part-slot">Item {index+1}</div><div className="part-icon">◇</div><div><span className="eyebrow">Engine maintenance</span><h2>{part.name.replace("Synthetic ", "")}</h2><p className="muted">Demonstration inventory · Record version {part.version}</p></div><div className="stock-number"><strong>{available}</strong><span>available now</span></div><div className="stock-state"><i className={constrained?"danger":"ready"}/><strong>{constrained?"Plan blocked":"Available"}</strong><span>{constrained?`Replenishment in ${part.lead_time_slots*8} hours`:"Can be reserved on approval"}</span></div><div className="stock-track"><i style={{width:`${Math.min(100,(available/Math.max(1,part.on_hand))*100)}%`}} /></div><div className="part-facts"><span><b>{part.on_hand}</b> on hand</span><span><b>{part.reserved}</b> reserved</span><span><b>{part.lead_time_slots * 8} hr</b> replenishment</span></div></article>;})}</div></AsyncState><p className="footnote">Inventory quantities and lead times are synthetic demonstration inputs. No purchase or supplier action is performed.</p></section>;
}
