import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { Link } from "react-router-dom";
import { api, arrayOf, isInventoryPart, type InventoryPart } from "../../shared/api/client";
import { Deliveries } from "./Deliveries";
import { AsyncState } from "../../shared/ui/AsyncState";
import { Icon } from "../../shared/ui/Icon";
import { Notice, PageHeader, RefreshButton, StatCard } from "../../shared/ui/WorkspaceUI";
export function InventoryPage() {
  const [search, setSearch] = useState("");
  const query = useQuery({ queryKey:["inventory"], queryFn: () => api<InventoryPart[]>("/inventory", undefined, arrayOf(isInventoryPart)) });
  const parts = query.data;
  const visible = parts?.filter((part) => `${part.id} ${part.name}`.toLowerCase().includes(search.trim().toLowerCase()));
  const available = (part: InventoryPart) => part.on_hand - part.reserved;
  const emptyStock = parts?.filter((part) => available(part) <= 0).length;
  return <section><PageHeader eyebrow="PARTS & LOGISTICS" title="Parts inventory" description="Inspect stock and committed reservations before generating or approving maintenance work." actions={<><RefreshButton fetching={query.isFetching} onClick={() => void query.refetch()}/><Link className="button" to="/planning"><Icon name="calendar" size={17}/>Open planning</Link></>}/>
    <div className="metric-grid"><StatCard label="Part types" value={parts?.length ?? "—"} detail="Registered inventory items" icon="box"/><StatCard label="Available units" value={parts?.reduce((sum,part) => sum + available(part),0) ?? "—"} detail="On hand minus active reservations" icon="check" tone="success"/><StatCard label="Reserved units" value={parts?.reduce((sum,part) => sum + part.reserved,0) ?? "—"} detail="Committed to approved plans" icon="calendar" tone="blue"/><StatCard label="Items with no free stock" value={emptyStock ?? "—"} detail="Check task requirements and arrivals" icon="warning" tone={emptyStock ? "warning" : "neutral"}/></div>
    {emptyStock !== undefined && emptyStock > 0 && <Notice title="Some inventory is fully committed" tone="warning">{emptyStock} item{emptyStock === 1 ? " has" : "s have"} no available stock. A configured lead time is an assumption; it does not confirm an incoming delivery.</Notice>}
    <Deliveries parts={parts ?? []}/>
    <article className="card"><div className="card-heading"><div><h2>Stock register</h2><p>Quantities are recorded in units. Approval rechecks the current version.</p></div><span className="source-tag">Synthetic logistics</span></div><div className="table-toolbar"><span className="muted">{parts ? `${parts.length} inventory items` : "Retrieving inventory"}</span><div className="search-field"><Icon name="search" size={17}/><label className="sr-only" htmlFor="parts-search">Search inventory</label><input id="parts-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search part name or ID…"/></div></div><AsyncState loading={query.isLoading} error={query.error} empty={!visible?.length} emptyMessage="No inventory matches this view" onRetry={() => void query.refetch()}><div className="table-scroll"><table><caption className="sr-only">Inventory stock and reservations</caption><thead><tr><th scope="col">Part</th><th scope="col">Available</th><th scope="col">On hand</th><th scope="col">Reserved</th><th scope="col">Assumed lead time</th><th scope="col">Stock status</th></tr></thead><tbody>{visible?.map((part) => <tr key={part.id}><td><div className="asset-cell"><span className="asset-icon"><Icon name="box" size={20}/></span><div><strong>{part.name}</strong><small className="mono">{part.id} · v{part.version}</small></div></div></td><td><strong className={available(part) <= 0 ? "warning-text" : "quantity"}>{available(part)}</strong></td><td>{part.on_hand}</td><td>{part.reserved}</td><td>{part.lead_time_slots * 8} hours<small className="table-subtitle">{part.lead_time_slots} planning slots</small></td><td><span className={`badge ${available(part)>0 ? "badge-normal" : "badge-warning"}`}><i/>{available(part)>0 ? "Available" : "No free stock"}</span></td></tr>)}</tbody></table></div><div className="table-footer"><span>{visible?.length} items shown</span><span>Stock is reserved only on approval</span></div></AsyncState></article><div className="logistics-note"><Icon name="file" size={19}/><p>Stock, maintenance durations and lead times are labelled demonstration inputs. Lead time does not create stock. No procurement or supplier action is performed.</p></div>
  </section>;
}
