import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { lazy, Suspense, useState, type FormEvent } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { PlanComparison } from '../planning/PlanComparison';
import { api, arrayOf, isComponentDetail, isJob, isPartArrival, isPlan, isPlanCommitment, isSimulationRun, type Job } from '../../shared/api/client';
import { AsyncState } from '../../shared/ui/AsyncState';
const AircraftScene = lazy(() => import('../inspection/AircraftScene').then(module => ({ default: module.AircraftScene })));
import { AssessmentSummary } from '../health/AssessmentSummary';
import { ModelEvidence } from '../health/ModelEvidence';
import { asRecord, isCatalog, isHistory, isTrial, type History } from './contracts';

const steps = ['Enter your case', 'Inspect AI evidence', 'Test maintenance options', 'Review & record work'];
const terminals = ['succeeded', 'failed', 'cancelled'];
const number = (v: unknown) => typeof v === 'number' && Number.isFinite(v) ? v : null;

export function CustomerTrialPage() {
  const [params, setParams] = useSearchParams();
  const trialId = params.get('trial');
  const client = useQueryClient();
  const [preview3D, setPreview3D] = useState(false);
  const [step, setStep] = useState(trialId ? 1 : 0), [error, setError] = useState<string | null>(null);
  const [label, setLabel] = useState('Customer aircraft'), [cutoff, setCutoff] = useState(140);
  const [usage, setUsage] = useState(12), [duration, setDuration] = useState(2), [deadline, setDeadline] = useState(14);
  const [stock, setStock] = useState(0), [arrival, setArrival] = useState(3);
  const [submittedJobs, setSubmittedJobs] = useState<Job[]>([]);
  const [uploaded, setUploaded] = useState<History | null>(null);
  const [commandId, setCommandId] = useState(() => `trial-${crypto.randomUUID().replaceAll('-', '')}`);
  const catalog = useQuery({ queryKey: ['trial-catalog'], queryFn: () => api('/demo/catalog', undefined, isCatalog), retry: false });
  const trials = useQuery({ queryKey: ['customer-trials'], queryFn: () => api('/demo/trials', undefined, arrayOf(isTrial)), enabled: !!catalog.data?.available });
  const trial = useQuery({ queryKey: ['customer-trial', trialId], queryFn: () => api(`/demo/trials/${trialId}`, undefined, isTrial), enabled: !!trialId, retry: false });
  const t = trial.data;
  const component = useQuery({ queryKey: ['trial-component', t?.component_id], queryFn: () => api(`/components/${t!.component_id}`, undefined, isComponentDetail), enabled: !!t, refetchInterval: 3000 });
  const plans = useQuery({ queryKey: ['trial-plans', trialId], queryFn: () => api(`/plans?scope_component_id=${encodeURIComponent(t!.component_id)}&limit=50`, undefined, arrayOf(isPlan)), enabled: !!t, refetchInterval: 3000 });
  const plan = plans.data?.find(p => asRecord(p.input_snapshot) && p.input_snapshot.scope_component_id === t?.component_id);
  const runs = useQuery({ queryKey: ['trial-runs', trialId], queryFn: async () => (await Promise.all([t!.baseline_scenario_id, t!.supply_scenario_id].map(id => api(`/scenarios/runs/all?scenario_id=${encodeURIComponent(id)}&limit=10`, undefined, arrayOf(isSimulationRun))))).flat(), enabled: !!t, refetchInterval: 3000 });
  const baseline = runs.data?.filter(r => r.scenario_id === t?.baseline_scenario_id).at(-1);
  const supply = runs.data?.filter(r => r.scenario_id === t?.supply_scenario_id).at(-1);
  const deliveries = useQuery({ queryKey: ['trial-arrivals', trialId], queryFn: () => api('/inventory/arrivals', undefined, arrayOf(isPartArrival)), enabled: !!t?.arrival_id, refetchInterval: 3000 });
  const delivery = deliveries.data?.find(d => d.id === t?.arrival_id);
  const commitment = useQuery({ queryKey: ['trial-commitment', plan?.id], queryFn: () => api(`/plans/${plan!.id}/commitment`, undefined, isPlanCommitment), enabled: !!plan, refetchInterval: 3000 });
  const jobs = useQuery({ queryKey: ['trial-jobs', trialId], queryFn: () => api(`/demo/trials/${trialId}/jobs`, undefined, arrayOf(isJob)), enabled: !!t, refetchInterval: 2000 });
  const observedSubmitted = submittedJobs.map(job => jobs.data?.find(j => j.id === job.id) ?? job);
  const activeJob = observedSubmitted.find(j => !terminals.includes(j.state)) ?? jobs.data?.find(j => !terminals.includes(j.state));
  const requestedPlanJob = submittedJobs.find(j => j.kind === 'planning');
  const latestPlanJob = requestedPlanJob ? jobs.data?.find(j => j.id === requestedPlanJob.id) : jobs.data?.find(j => j.kind === 'planning');
  const proposalCurrent = plan?.id === latestPlanJob?.result?.plan_id;
  const assessment = component.data?.assessment;
  const matched = !!t && !!assessment && assessment.input_version === t.import_id && assessment.model_version === t.model_id;
  const available = matched && assessment.state === 'available' && assessment.lower_cycles !== null;
  const forecastHours = available ? assessment.lower_cycles! * 24 / t.cycles_per_day : null;
  const snapshot = asRecord(plan?.input_snapshot) ? plan.input_snapshot : null;
  const advisory = asRecord(snapshot?.advisory) ? snapshot.advisory : null;
  const work = commitment.data?.work[0];
  const readyToApprove = proposalCurrent && plan?.status === 'proposed' && !!baseline && !!supply && (!t?.arrival_id || delivery?.status === 'received');
  const inputHistory = uploaded ?? catalog.data?.history;
  const latestFailed = jobs.data?.[0]?.state === 'failed' || jobs.data?.[0]?.state === 'cancelled';
  const action = useMutation({
    mutationFn: async (call: () => Promise<unknown>) => call(),
    onMutate: () => setError(null),
    onSuccess: () => client.invalidateQueries({ predicate: q => String(q.queryKey[0]).startsWith('trial-') || q.queryKey[0] === 'customer-trials' }),
    onError: e => setError(e instanceof Error ? e.message : 'The action could not be completed.'),
  });
  const busy = action.isPending || !!activeJob;
  const post = (path: string, body?: unknown) => api(path, { method: 'POST', ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
  const submitJob = async (path: string, body?: unknown) => {
    const job = await api<Job>(path, { method: 'POST', ...(body === undefined ? {} : { body: JSON.stringify(body) }) }, isJob);
    setSubmittedJobs(previous => [job, ...previous]);
    return job;
  };
  const openTrial = (id: string) => { setSubmittedJobs([]); setParams({ trial: id }); setStep(1); setError(null); };
  const newTrial = () => { setSubmittedJobs([]); setParams({}); setStep(0); setError(null); setCommandId(`trial-${crypto.randomUUID().replaceAll('-', '')}`); };
  const create = (event: FormEvent) => {
    event.preventDefault();
    action.mutate(async () => {
      const created = await api('/demo/trials', { method: 'POST', body: JSON.stringify({ id: commandId, aircraft_label: label, cutoff_cycle: cutoff, cycles_per_day: usage, duration_slots: duration, deadline_slot: deadline, spare_on_hand: stock, arrival_slot: arrival, ...(uploaded ? { history: uploaded } : {}) }) }, isTrial);
      openTrial(created.id);
    });
  };
  const upload = async (file?: File) => {
    if (!file) return;
    setError(null);
    try {
      if (file.size > 8_000_000) throw new Error('Use a history file under 8 MB.');
      const value: unknown = JSON.parse(await file.text());
      if (!isHistory(value)) throw new Error('Use FD001 history JSON: engine_identity, source_version and consecutive rows of 24 numeric values (or null for missing data).');
      setUploaded(value); setCutoff(Math.min(140, value.rows.length));
    } catch (e) { setError(e instanceof Error ? e.message : 'History file could not be read.'); }
  };
  const download = async () => {
    const history = t ? await api(`/demo/trials/${t.id}/history`, undefined, isHistory) : inputHistory;
    if (!history) return;
    const url = URL.createObjectURL(new Blob([JSON.stringify(history, null, 2)], { type: 'application/json' }));
    const a = document.createElement('a'); a.href = url; a.download = 'simulated-fd001-history.json'; a.click(); URL.revokeObjectURL(url);
  };
  const selectedStep = step;
  return <section className="customer-trial">
    <div className="trial-heading"><div><span className="eyebrow">INTERACTIVE CUSTOMER TRIAL</span><h1>From engine data to a maintenance decision.</h1><p>Bring a case. Change the assumptions. See what the evidence and constraints allow.</p></div>{t && <button className="button-secondary" onClick={newTrial} disabled={busy}>Try another case</button>}</div>
    <ol className="trial-progress" aria-label="Customer trial steps">{steps.map((name, i) => <li key={name}><button onClick={() => setStep(i)} aria-current={selectedStep === i ? 'step' : undefined} disabled={i > 0 && !t || i === 3 && !plan}><span>{i + 1}</span>{name}</button></li>)}</ol>
    {error && <div className="trial-error" role="alert"><strong>Action needs attention</strong><p>{error}</p></div>}
    {trial.error && <AsyncState loading={false} error={trial.error} onRetry={() => void trial.refetch()}><span/></AsyncState>}
    {trialId && trial.isPending && <p role="status">Opening saved trial…</p>}
    {activeJob && <div className="trial-job" role="status"><span className="spinner"/><div><strong>{activeJob.kind === 'assessment' ? 'Calculating the AI assessment' : activeJob.kind === 'planning' ? 'Checking the schedule constraints' : 'Simulating entered assumptions'}</strong><p>{activeJob.state} · Results are saved on the server. You can return to this trial.</p><small>{activeJob.id}</small></div></div>}
    {jobs.error && <p role="alert">Job progress is unavailable. Reload before retrying a calculation.</p>}
    {latestFailed && !activeJob && <p className="quality-finding" role="alert">The last calculation {jobs.data?.[0]?.state}. Review inputs and retry the relevant step; no result has been substituted.</p>}
    {(!t || selectedStep === 0) && <div className="trial-entry-grid"><article className="trial-aircraft"><div><span className="eyebrow">YOUR MAINTENANCE WORKSPACE</span><h2>Start with the engine.</h2><p>Select the mapped engine to enter its data. Explore the interactive aircraft when you want a closer view.</p></div>{preview3D ? <Suspense fallback={<p className="state">Loading illustrative aircraft. Engine evidence and actions remain available alongside.</p>}><AircraftScene components={[{ id: t?.component_id ?? 'trial-engine', label: 'Engine · customer trial' }]} selected={t?.component_id ?? 'trial-engine'} onSelect={() => { if (t) setStep(1); else document.getElementById('trial-inputs')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }}/></Suspense> : <><img src="/models/aircraft-poster.png" alt="Illustrative aircraft for this customer case" style={{width:'100%',height:320,objectFit:'contain'}}/><button className="button-secondary" onClick={() => { if (t) setStep(1); else document.getElementById('trial-cutoff')?.focus(); }}>Engine · customer trial</button><button className="text-link" onClick={() => setPreview3D(true)}>Explore interactive aircraft</button></>}</article>
      <article className="card trial-input-card" id="trial-inputs"><span className="eyebrow">01 · ENTER YOUR CASE</span><h2>What should we test?</h2><p>Preloaded with a simulated engine history. Every new case gets its own synthetic aircraft, inspection task, stock and crew.</p>
        {t ? <><dl className="trial-saved-inputs"><dt>Aircraft / customer</dt><dd>{t.aircraft_label}</dd><dt>Supplied engine history</dt><dd>{t.engine_identity} · through cycle {t.cutoff_cycle}</dd><dt>Usage assumption</dt><dd>{t.cycles_per_day} cycles / day</dd><dt>Inspection duration / mandatory deadline</dt><dd>{t.duration_slots * 8}h / hour {t.deadline_slot * 8}</dd><dt>Initial kits / expected delivery</dt><dd>{t.spare_on_hand} kit(s) / hour {t.arrival_slot * 8}</dd></dl><button className="button-secondary" onClick={() => action.mutate(download)}>Download entered history</button><p className="footnote">Saved inputs stay with this case. Create another case to test changes.</p><button className="button" onClick={() => setStep(1)}>Return to AI evidence</button></> : <AsyncState loading={catalog.isPending} error={catalog.error} onRetry={() => void catalog.refetch()} empty={catalog.data?.available === false} emptyMessage={catalog.data?.reason ?? 'Trial data unavailable'}>
          <form onSubmit={create} className="trial-form"><label>Aircraft / customer name<input required maxLength={80} value={label} onChange={e => setLabel(e.target.value)}/></label>
            <div className="trial-history"><strong>{uploaded ? 'Your supplied history' : 'NASA C-MAPSS · simulated FD001 engine'}</strong><p>{inputHistory?.engine_identity} · {inputHistory?.rows.length ?? '—'} available cycles</p><label htmlFor="trial-cutoff">History through cycle<input id="trial-cutoff" type="number" required min={1} max={inputHistory?.rows.length ?? 180} step={1} value={cutoff} onChange={e => setCutoff(Number(e.target.value))}/></label><input type="range" aria-label="Adjust history cutoff" min={1} max={inputHistory?.rows.length ?? 180} value={cutoff} onChange={e => setCutoff(Number(e.target.value))}/><p className="footnote">Only observations through this cycle enter the AI. Below 30 cycles, the assessment is withheld.</p><div className="trial-inline-actions"><button type="button" className="text-link" onClick={() => action.mutate(download)}>Download / inspect history</button><label className="text-link upload-label">Use a history JSON file<input type="file" accept=".json,application/json" onChange={e => void upload(e.target.files?.[0])}/></label>{uploaded && <button type="button" onClick={() => { setUploaded(null); setCutoff(140); }}>Use sample again</button>}</div></div>
            <div className="trial-form-grid"><label>Usage (cycles / day)<input type="number" min={0.1} max={120} step={0.1} required value={usage} onChange={e => setUsage(Number(e.target.value))}/></label><label>Inspection duration<select value={duration} onChange={e => setDuration(Number(e.target.value))}>{[1,2,3,4,6,8,10,12,14].map(n => <option key={n} value={n}>{n * 8} hours</option>)}</select></label><label>Mandatory deadline<select value={deadline} onChange={e => setDeadline(Number(e.target.value))}>{Array.from({length:14},(_,i)=>i+1).map(n => <option key={n} value={n}>Hour {n * 8}</option>)}</select></label><label>Inspection kits in stock<input type="number" required min={0} max={10} step={1} value={stock} onChange={e => setStock(Number(e.target.value))}/></label>{stock === 0 && <label>Expected kit delivery<select value={arrival} onChange={e => setArrival(Number(e.target.value))}>{Array.from({length:14},(_,i)=>i).map(n => <option key={n} value={n}>Hour {n * 8}</option>)}</select></label>}</div>
            <p className="footnote">Synthetic logistics · One dedicated engine crew and compatible bay · 112-hour horizon · 8-hour scheduling slots. An expected delivery is not received stock.</p><button className="button" type="submit" disabled={busy || !catalog.data?.available || !!t}>Create my trial</button>{t && <p>Create another case to change these inputs while keeping previous results.</p>}
          </form>
        </AsyncState>}
      </article></div>}
    {t && selectedStep > 0 && <><div className="trial-case-bar"><div><strong>{t.aircraft_label}</strong><span>{t.history_origin} · cycle {t.cutoff_cycle} · {t.cycles_per_day} cycles/day</span></div><span>{t.spare_on_hand} kit(s) initially in stock · {t.duration_slots * 8}h inspection · deadline {t.deadline_slot * 8}h</span><button className="text-link" onClick={() => setStep(0)}>View entered data</button></div>
      {selectedStep === 1 && <div className="trial-evidence-grid"><article className="trial-aircraft"><Suspense fallback={<p className="state">Loading illustrative aircraft. Engine evidence and actions remain available alongside.</p>}><AircraftScene components={[{id:t.component_id,label:'Engine · AI evidence'}]} selected={t.component_id} onSelect={() => document.getElementById('trial-evidence')?.scrollIntoView({behavior:'smooth'})}/></Suspense><Link className="text-link" to={`/components/${t.component_id}`}>Open full component history & evidence</Link></article><article className="card trial-evidence" id="trial-evidence"><span className="eyebrow">02 · INSPECT AI EVIDENCE</span><h2>What does this engine history suggest?</h2><p>The fitted model reads the supplied operating settings and sensor history. Its estimate and interval stay in cycles.</p><AsyncState loading={component.isPending} error={component.error} onRetry={() => void component.refetch()}><AssessmentSummary assessment={matched ? assessment : null}/>{assessment?.quality_findings.map(f => <p className="quality-finding" key={f.code}>{f.message}</p>)}{forecastHours !== null && <p className="trial-insight">At your entered {t.cycles_per_day} cycles/day, the lower interval endpoint projects to <strong>{forecastHours.toFixed(1)} hours</strong>. The trial uses this to bound a synthetic review window; it is not a failure forecast.</p>}<button className="button" disabled={busy} onClick={() => action.mutate(() => submitJob('/jobs/assessment', {import_id:t.import_id,model_id:t.model_id,cutoff_cycle:t.cutoff_cycle}))}>{matched ? 'Recalculate AI assessment' : 'Calculate AI assessment'}</button>{available && <button className="button-secondary" onClick={() => setStep(2)}>Use this evidence to test options</button>}</AsyncState>{matched && <details><summary>Inspect model, input and explanation</summary><ModelEvidence assessment={assessment} componentId={t.component_id}/></details>}</article></div>}
      {selectedStep === 2 && <div className="trial-options"><article className="card"><span className="eyebrow">03 · TEST MAINTENANCE OPTIONS</span><h2>Can the inspection fit your constraints?</h2><p>The planner checks your task duration, qualified crew and bay, parts readiness and mandatory deadline. AI informs a review window under your declared usage.</p><div className="trial-constraint-list"><div><span>Work duration</span><strong>{t.duration_slots * 8} hours</strong></div><div><span>Mandatory deadline</span><strong>Hour {t.deadline_slot * 8}</strong></div><div><span>Kit ready</span><strong>{t.spare_on_hand > 0 || delivery?.status === 'received' ? 'Received stock' : `Expected at hour ${t.arrival_slot * 8}`}</strong></div><div><span>AI-informed review window</span><strong>{forecastHours === null ? 'Assessment required' : `By hour ${Math.min(t.deadline_slot,Math.floor(forecastHours/8)) * 8}`}</strong></div></div><p className="footnote">Trial policy v1: lower interval endpoint × 24 ÷ cycles/day; round down to 8-hour slots and use the earlier of this window and your mandatory deadline. This is a demonstration assumption requiring human review.</p><button className="button" disabled={busy || !available || !!work} onClick={() => action.mutate(() => submitJob(`/demo/trials/${t.id}/planning`))}>{plan ? 'Recalculate schedule' : 'Calculate my schedule'}</button>
          {plan && <div className="trial-schedule-result"><h3>{plan.status === 'proposed' ? 'A usable schedule was found' : plan.status === 'approved' ? 'Schedule approved' : 'No usable schedule available'}</h3><p>Solver: {plan.solver_status}</p>{plan.assignments.map(a => <div className="trial-timeline" key={a.task_id}><span>Hour {a.start * 8}</span><strong>Engine inspection · {(a.end-a.start)*8}h</strong><span>Hour {a.end * 8}</span></div>)}{plan.diagnostics.map(d => <p className="quality-finding" key={d}>{d}</p>)}{advisory && <p className="footnote">Linked assessment {String(advisory.assessment_id)} · Effective deadline {String(advisory.effective_deadline_hours)} hours</p>}{!plan.assignments.length && <p>Try another case with a shorter inspection, an earlier spare delivery or a feasible usage/window assumption. Hard constraints stay active.</p>}</div>}
        </article><article className="card"><span className="eyebrow">COMPARE THE CONSEQUENCE</span><h2>What does waiting for a spare change?</h2><p>Run the same one-aircraft, {t.duration_slots*8}-hour inspection over 112 hours: a kit ready now versus your entered supply. This tests logistics; it does not simulate a predicted failure or a repair benefit.</p><button className="button-secondary" disabled={busy || !available} onClick={() => action.mutate(async () => { await submitJob(`/jobs/simulation/${t.baseline_scenario_id}`); await submitJob(`/jobs/simulation/${t.supply_scenario_id}`); })}>Run parts comparison</button>{baseline && supply && <><div className="table-scroll"><table><caption>Simulated projections · matched workload</caption><thead><tr><th>Result</th><th>Kit ready now</th><th>Your entered supply</th></tr></thead><tbody><tr><th>Downtime (aircraft hours)</th><td>{number(baseline.metrics.downtime_aircraft_hours)?.toFixed(1) ?? 'Unavailable'}</td><td>{number(supply.metrics.downtime_aircraft_hours)?.toFixed(1) ?? 'Unavailable'}</td></tr><tr><th>Waiting for parts (hours)</th><td>{number(baseline.metrics.part_wait_hours)?.toFixed(1) ?? 'Unavailable'}</td><td>{number(supply.metrics.part_wait_hours)?.toFixed(1) ?? 'Unavailable'}</td></tr><tr><th>Time available</th><td>{(baseline.availability*100).toFixed(1)}%</td><td>{(supply.availability*100).toFixed(1)}%</td></tr></tbody></table></div><p className="trial-insight">Your input determines the outcome: {t.spare_on_hand ? 'a kit was already in stock, so both supply cases are the same.' : `the entered ${t.arrival_slot*8}-hour delivery wait adds time before maintenance can begin.`}</p><p className="footnote">Recorded inputs remain the original comparison even after a demo receipt. Deterministic simulation · seed {supply.seed} · each result links to its saved scenario.</p></>}{plan?.assignments.length && baseline && supply ? <button className="button" onClick={() => setStep(3)}>Review this decision</button> : null}</article></div>}
      {selectedStep >= 2 && plan && ['optimal','feasible'].includes(plan.solver_status) && <PlanComparison key={plan.id} planId={plan.id}/>}
      {selectedStep === 3 && <article className="card trial-review"><span className="eyebrow">04 · REVIEW & RECORD WORK</span><h2>A person makes the maintenance decision.</h2><p>Review the computed evidence and schedule, then explicitly approve this synthetic trial. Approval reserves a real demo kit and creates a work record.</p><div className="trial-review-summary"><AssessmentSummary assessment={matched ? assessment : null}/><div><h3>{t.aircraft_label} · engine inspection</h3><p>{plan?.assignments.map(a => `Hour ${a.start*8}–${a.end*8}`).join(', ') || 'No usable assignment'} · {plan?.solver_status}</p><p>{baseline && supply ? `Simulated downtime: ${number(baseline.metrics.downtime_aircraft_hours)?.toFixed(1) ?? '—'}h with ready stock; ${number(supply.metrics.downtime_aircraft_hours)?.toFixed(1) ?? '—'}h under entered supply.` : 'Complete the parts comparison before approval.'}</p><button className="text-link" onClick={() => setStep(2)}>Return to options & comparison</button></div></div>
        {t.arrival_id && delivery?.status === 'expected' && <div className="trial-receipt"><strong>The kit is expected, not received.</strong><p>Record a synthetic delivery receipt, then recalculate the schedule against current stock. An old proposal will be rejected.</p><button className="button-secondary" disabled={busy} onClick={() => action.mutate(async () => { await post(`/inventory/arrivals/${t.arrival_id}/outcome`, {action:'receive',expected_version:delivery.version,reason:'Customer recorded a synthetic trial delivery receipt'}); await submitJob(`/demo/trials/${t.id}/planning`); })}>Record demo receipt & replan</button></div>}
        {!work && <button className="button" disabled={busy || !readyToApprove} onClick={() => plan && action.mutate(() => post(`/plans/${plan.id}/approve`))}>Approve this demo plan</button>}
        {commitment.error && <p role="alert">Work status is unavailable. Reload before recording another outcome.</p>}
        {work && <div className="trial-work"><h3>Work record · {work.status.replaceAll('_',' ')}</h3><p>{commitment.data?.reservations.map(r => `${r.quantity} kit · ${r.status}`).join(', ') || 'No part reservations recorded'}</p><p>Consumed: {work.consumed_quantity} kit(s)</p>{work.status === 'approved' && <button className="button" disabled={busy} onClick={() => action.mutate(() => post(`/work/${work.id}/outcome`,{action:'start',expected_version:work.version,notes:'Customer started synthetic trial work'}))}>Record work started</button>}{work.status === 'in_progress' && <button className="button" disabled={busy} onClick={() => action.mutate(() => post(`/work/${work.id}/outcome`,{action:'complete',expected_version:work.version,notes:'Customer completed synthetic trial inspection; no aircraft clearance'}))}>Record inspection completed</button>}{work.status === 'completed' && <div className="trial-complete"><strong>You’ve followed the full decision flow.</strong><p>Your entered engine data produced an AI estimate; declared constraints produced a schedule; matched supply cases produced projections; human approval reserved the kit; recorded work consumed it.</p><button className="button-secondary" onClick={newTrial}>Change inputs & try another case</button></div>}</div>}
        <details><summary>Trace this decision to saved records</summary><dl><dt>Trial</dt><dd>{t.id}</dd><dt>Imported history</dt><dd>{t.import_id} · SHA256 {t.history_sha256}</dd><dt>Model</dt><dd>{t.model_id} · research model, qualification pending</dd><dt>Plan</dt><dd>{plan?.id ?? 'Unavailable'}</dd><dt>Comparison runs</dt><dd>{baseline?.id ?? 'Unavailable'} / {supply?.id ?? 'Unavailable'}</dd><dt>Work record</dt><dd>{work?.id ?? 'Not approved'}</dd></dl></details><p className="footnote">Demo supervisor actions affect synthetic records only. They do not provide aircraft clearance.</p>
      </article>}
    </>}
    <details className="trial-library"><summary>Reopen a saved customer trial ({trials.data?.length ?? 0})</summary>{trials.error && <p role="alert">Saved trials could not be loaded.</p>}{trials.data?.map(saved => <button className="button-secondary" disabled={busy} key={saved.id} onClick={() => openTrial(saved.id)}>{saved.aircraft_label} · cycle {saved.cutoff_cycle} · {saved.id.slice(6,14)}</button>)}</details>
  </section>;
}
