"""fleet health workspace decisions

Revision ID: 4171f79fe2a6
Revises: f537880a4c71
Create Date: 2026-10-05 18:52:50.158866
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4171f79fe2a6'
down_revision: Union[str, Sequence[str], None] = 'f537880a4c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fleet_advisory_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('advisory_id', sa.String(length=96), nullable=False),
    sa.Column('component_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('work_order_id', sa.String(length=64), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status <> 'dismissed' OR reason IS NOT NULL", name='ck_fleet_dismiss_reason'),
    sa.CheckConstraint("status IN ('proposed', 'accepted', 'scheduled', 'completed', 'dismissed')", name='ck_fleet_advisory_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fleet_advisory_decisions_advisory_created', 'fleet_advisory_decisions', ['advisory_id', 'created_at'], unique=False)
    op.create_table('fleet_alert_acknowledgements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_key', sa.String(length=128), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fleet_alert_acknowledgements_alert_key'), 'fleet_alert_acknowledgements', ['alert_key'], unique=False)
    op.create_table('fleet_engine_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=True),
    sa.Column('artifact_directory', sa.String(length=255), nullable=True),
    sa.Column('hashes', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('queued', 'succeeded', 'failed')", name='ck_fleet_run_state'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fleet_engine_runs_job_id'), 'fleet_engine_runs', ['job_id'], unique=False)
    op.create_table('fleet_ingest_batches',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('accepted', sa.Integer(), nullable=False),
    sa.Column('rejected', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fleet_work_orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('advisory_id', sa.String(length=96), nullable=True),
    sa.Column('aircraft', sa.String(length=16), nullable=False),
    sa.Column('component_id', sa.String(length=64), nullable=True),
    sa.Column('agency_id', sa.String(length=16), nullable=False),
    sa.Column('part', sa.String(length=16), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('planned_start', sa.Date(), nullable=False),
    sa.Column('duration_days', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=4), nullable=True),
    sa.Column('impact', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'in_progress', 'completed', 'cancelled')", name='ck_fleet_work_order_status'),
    sa.CheckConstraint('duration_days > 0', name='ck_fleet_work_order_duration'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fleet_work_orders_advisory_id'), 'fleet_work_orders', ['advisory_id'], unique=False)
    op.create_index('ix_fleet_work_orders_status_agency', 'fleet_work_orders', ['status', 'agency_id'], unique=False)
    op.create_table('fleet_ingested_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('component_id', sa.String(length=64), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('parameter', sa.String(length=64), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('maximum', sa.Float(), nullable=True),
    sa.Column('minimum', sa.Float(), nullable=True),
    sa.Column('std', sa.Float(), nullable=True),
    sa.Column('quality_flag', sa.Integer(), nullable=False),
    sa.CheckConstraint('quality_flag IN (0, 1, 2, 3)', name='ck_fleet_reading_quality'),
    sa.ForeignKeyConstraint(['batch_id'], ['fleet_ingest_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fleet_ingested_component_date', 'fleet_ingested_readings', ['component_id', 'reading_date'], unique=False)
    op.create_table('fleet_scenario_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('engine_run_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engine_run_id'], ['fleet_engine_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fleet_scenario_runs')
    op.drop_index('ix_fleet_ingested_component_date', table_name='fleet_ingested_readings')
    op.drop_table('fleet_ingested_readings')
    op.drop_index('ix_fleet_work_orders_status_agency', table_name='fleet_work_orders')
    op.drop_index(op.f('ix_fleet_work_orders_advisory_id'), table_name='fleet_work_orders')
    op.drop_table('fleet_work_orders')
    op.drop_table('fleet_ingest_batches')
    op.drop_index(op.f('ix_fleet_engine_runs_job_id'), table_name='fleet_engine_runs')
    op.drop_table('fleet_engine_runs')
    op.drop_index(op.f('ix_fleet_alert_acknowledgements_alert_key'), table_name='fleet_alert_acknowledgements')
    op.drop_table('fleet_alert_acknowledgements')
    op.drop_index('ix_fleet_advisory_decisions_advisory_created', table_name='fleet_advisory_decisions')
    op.drop_table('fleet_advisory_decisions')
    # ### end Alembic commands ###
