"""initial_schema

Revision ID: 605fbc678b90
Revises:
Create Date: 2026-10-03 19:20:14.932047
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "605fbc678b90"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aircraft",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tail_number", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("provenance", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tail_number"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("subject_id", sa.String(length=80), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=48), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("input_payload", sa.JSON(), nullable=False),
        sa.Column("result_payload", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("topic", sa.String(length=80), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "parts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("on_hand", sa.Integer(), nullable=False),
        sa.Column("lead_time_slots", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plans",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("solver_status", sa.String(length=32), nullable=False),
        sa.Column("input_version", sa.String(length=128), nullable=False),
        sa.Column("assignments", sa.JSON(), nullable=False),
        sa.Column("diagnostics", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("approved_by", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scenarios",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("assumptions", sa.JSON(), nullable=False),
        sa.Column("provenance", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "simulation_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("scenario_id", sa.String(length=64), nullable=False),
        sa.Column("policy", sa.String(length=64), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("availability", sa.Float(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_simulation_runs_scenario_id"), "simulation_runs", ["scenario_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "components",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("aircraft_id", sa.String(length=64), nullable=False),
        sa.Column("serial_number", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current_cycle", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["aircraft_id"],
            ["aircraft.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("serial_number"),
    )
    op.create_index(op.f("ix_components_aircraft_id"), "components", ["aircraft_id"], unique=False)
    op.create_table(
        "reservations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("plan_id", sa.String(length=64), nullable=False),
        sa.Column("part_id", sa.String(length=64), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["parts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "part_id", name="uq_plan_part_reservation"),
    )
    op.create_index(op.f("ix_reservations_part_id"), "reservations", ["part_id"], unique=False)
    op.create_index(op.f("ix_reservations_plan_id"), "reservations", ["plan_id"], unique=False)
    op.create_table(
        "alerts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("component_id", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=240), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("assessment_id", sa.String(length=64), nullable=True),
        sa.Column("acknowledged_by", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["components.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_component_id"), "alerts", ["component_id"], unique=False)
    op.create_table(
        "assessments",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("component_id", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("estimate_cycles", sa.Float(), nullable=True),
        sa.Column("lower_cycles", sa.Float(), nullable=True),
        sa.Column("upper_cycles", sa.Float(), nullable=True),
        sa.Column("model_version", sa.String(length=80), nullable=True),
        sa.Column("input_version", sa.String(length=120), nullable=False),
        sa.Column("quality_findings", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["components.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assessments_component_id"), "assessments", ["component_id"], unique=False
    )
    op.create_table(
        "maintenance_tasks",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("component_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("duration_slots", sa.Integer(), nullable=False),
        sa.Column("earliest_slot", sa.Integer(), nullable=False),
        sa.Column("deadline_slot", sa.Integer(), nullable=False),
        sa.Column("required_skill", sa.String(length=64), nullable=False),
        sa.Column("required_part_id", sa.String(length=64), nullable=True),
        sa.Column("required_part_quantity", sa.Integer(), nullable=False),
        sa.Column("mandatory", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["components.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_maintenance_tasks_component_id"),
        "maintenance_tasks",
        ["component_id"],
        unique=False,
    )
    op.create_table(
        "observations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("component_id", sa.String(length=64), nullable=False),
        sa.Column("cycle", sa.Integer(), nullable=False),
        sa.Column("sensor", sa.String(length=40), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=24), nullable=False),
        sa.Column("source_version", sa.String(length=80), nullable=False),
        sa.Column("observed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["components.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("component_id", "cycle", "sensor", name="uq_observation"),
    )
    op.create_index(
        op.f("ix_observations_component_id"), "observations", ["component_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_observations_component_id"), table_name="observations")
    op.drop_table("observations")
    op.drop_index(op.f("ix_maintenance_tasks_component_id"), table_name="maintenance_tasks")
    op.drop_table("maintenance_tasks")
    op.drop_index(op.f("ix_assessments_component_id"), table_name="assessments")
    op.drop_table("assessments")
    op.drop_index(op.f("ix_alerts_component_id"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_reservations_plan_id"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_part_id"), table_name="reservations")
    op.drop_table("reservations")
    op.drop_index(op.f("ix_components_aircraft_id"), table_name="components")
    op.drop_table("components")
    op.drop_table("users")
    op.drop_index(op.f("ix_simulation_runs_scenario_id"), table_name="simulation_runs")
    op.drop_table("simulation_runs")
    op.drop_table("scenarios")
    op.drop_table("plans")
    op.drop_table("parts")
    op.drop_table("outbox_events")
    op.drop_table("jobs")
    op.drop_table("audit_events")
    op.drop_table("aircraft")
    # ### end Alembic commands ###
