"""fleet part requests

Revision ID: 61a3e0ef5591
Revises: 4171f79fe2a6
Create Date: 2026-10-06 15:08:22.836522
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '61a3e0ef5591'
down_revision: Union[str, Sequence[str], None] = '4171f79fe2a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fleet_part_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('work_order_id', sa.String(length=64), nullable=False),
    sa.Column('part', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('needed_by', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status <> 'ordered' OR eta IS NOT NULL", name='ck_fleet_part_eta'),
    sa.CheckConstraint("status IN ('open', 'reserved', 'ordered', 'received', 'cancelled')", name='ck_fleet_part_request_status'),
    sa.CheckConstraint('quantity > 0', name='ck_fleet_part_quantity'),
    sa.ForeignKeyConstraint(['work_order_id'], ['fleet_work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fleet_part_requests_part'), 'fleet_part_requests', ['part'], unique=False)
    op.create_index(op.f('ix_fleet_part_requests_work_order_id'), 'fleet_part_requests', ['work_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fleet_part_requests_work_order_id'), table_name='fleet_part_requests')
    op.drop_index(op.f('ix_fleet_part_requests_part'), table_name='fleet_part_requests')
    op.drop_table('fleet_part_requests')
    # ### end Alembic commands ###
