"""store timestamps with explicit UTC timezone semantics

Revision ID: 64c201993bc1
Revises: 869651fc3441
Create Date: 2026-10-04 14:49:55.399365
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "64c201993bc1"
down_revision: Union[str, Sequence[str], None] = "869651fc3441"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # SQLite has no timezone column type; its development timestamps remain UTC by convention.
    if op.get_bind().dialect.name == "sqlite":
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assessments",
        "created_at",
        postgresql_using="\"created_at\" AT TIME ZONE 'UTC'",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "audit_events",
        "created_at",
        postgresql_using="\"created_at\" AT TIME ZONE 'UTC'",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "command_records",
        "created_at",
        postgresql_using="\"created_at\" AT TIME ZONE 'UTC'",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "import_records",
        "created_at",
        postgresql_using="\"created_at\" AT TIME ZONE 'UTC'",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "lease_expires_at",
        postgresql_using="\"lease_expires_at\" AT TIME ZONE 'UTC'",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "jobs",
        "started_at",
        postgresql_using="\"started_at\" AT TIME ZONE 'UTC'",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "jobs",
        "finished_at",
        postgresql_using="\"finished_at\" AT TIME ZONE 'UTC'",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "jobs",
        "created_at",
        postgresql_using="\"created_at\" AT TIME ZONE 'UTC'",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "login_sessions",
        "expires_at",
        postgresql_using="\"expires_at\" AT TIME ZONE 'UTC'",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "login_sessions",
        "created_at",
        postgresql_using="\"created_at\" AT TIME ZONE 'UTC'",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "model_registrations",
        "created_at",
        postgresql_using="\"created_at\" AT TIME ZONE 'UTC'",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "observations",
        "observed_at",
        postgresql_using="\"observed_at\" AT TIME ZONE 'UTC'",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "outbox_events",
        "published_at",
        postgresql_using="\"published_at\" AT TIME ZONE 'UTC'",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "plans",
        "created_at",
        postgresql_using="\"created_at\" AT TIME ZONE 'UTC'",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "plans",
        "approved_at",
        postgresql_using="\"approved_at\" AT TIME ZONE 'UTC'",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "locked_until",
        postgresql_using="\"locked_until\" AT TIME ZONE 'UTC'",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "work_records",
        "started_at",
        postgresql_using="\"started_at\" AT TIME ZONE 'UTC'",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "work_records",
        "completed_at",
        postgresql_using="\"completed_at\" AT TIME ZONE 'UTC'",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    if op.get_bind().dialect.name == "sqlite":
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "work_records",
        "completed_at",
        postgresql_using="\"completed_at\" AT TIME ZONE 'UTC'",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "work_records",
        "started_at",
        postgresql_using="\"started_at\" AT TIME ZONE 'UTC'",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "locked_until",
        postgresql_using="\"locked_until\" AT TIME ZONE 'UTC'",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "plans",
        "approved_at",
        postgresql_using="\"approved_at\" AT TIME ZONE 'UTC'",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "plans",
        "created_at",
        postgresql_using="\"created_at\" AT TIME ZONE 'UTC'",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "outbox_events",
        "published_at",
        postgresql_using="\"published_at\" AT TIME ZONE 'UTC'",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "observations",
        "observed_at",
        postgresql_using="\"observed_at\" AT TIME ZONE 'UTC'",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "model_registrations",
        "created_at",
        postgresql_using="\"created_at\" AT TIME ZONE 'UTC'",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "login_sessions",
        "created_at",
        postgresql_using="\"created_at\" AT TIME ZONE 'UTC'",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "login_sessions",
        "expires_at",
        postgresql_using="\"expires_at\" AT TIME ZONE 'UTC'",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "created_at",
        postgresql_using="\"created_at\" AT TIME ZONE 'UTC'",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "finished_at",
        postgresql_using="\"finished_at\" AT TIME ZONE 'UTC'",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "jobs",
        "started_at",
        postgresql_using="\"started_at\" AT TIME ZONE 'UTC'",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "jobs",
        "lease_expires_at",
        postgresql_using="\"lease_expires_at\" AT TIME ZONE 'UTC'",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "import_records",
        "created_at",
        postgresql_using="\"created_at\" AT TIME ZONE 'UTC'",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "command_records",
        "created_at",
        postgresql_using="\"created_at\" AT TIME ZONE 'UTC'",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "audit_events",
        "created_at",
        postgresql_using="\"created_at\" AT TIME ZONE 'UTC'",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "assessments",
        "created_at",
        postgresql_using="\"created_at\" AT TIME ZONE 'UTC'",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
