"""durable work records sessions and versioned evidence

Revision ID: 869651fc3441
Revises: 2e4a7d81b6c3
Create Date: 2026-10-04 06:05:38.477752
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '869651fc3441'
down_revision: Union[str, Sequence[str], None] = '2e4a7d81b6c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_records',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('result_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_registrations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('artifact_directory', sa.String(length=240), nullable=False),
    sa.Column('hashes', sa.JSON(), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_login_sessions_user_id'), 'login_sessions', ['user_id'], unique=False)
    op.create_table('import_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('component_id', sa.String(length=64), nullable=False),
    sa.Column('source_version', sa.String(length=80), nullable=False),
    sa.Column('engine_identity', sa.String(length=120), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('rows', sa.JSON(), nullable=False),
    sa.Column('previous_id', sa.String(length=64), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['previous_id'], ['import_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id', 'source_version', name='uq_import_version')
    )
    op.create_index(op.f('ix_import_records_component_id'), 'import_records', ['component_id'], unique=False)
    op.create_table('work_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('consumed_quantity', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['maintenance_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'task_id', name='uq_plan_work_task')
    )
    op.create_index(op.f('ix_work_records_plan_id'), 'work_records', ['plan_id'], unique=False)
    op.create_index(op.f('ix_work_records_task_id'), 'work_records', ['task_id'], unique=False)
    op.add_column('assessments', sa.Column('evidence', sa.JSON(), server_default='{}', nullable=False))
    op.add_column('assessments', sa.Column('cutoff_cycle', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('owner', sa.String(length=64), server_default='demo-planner', nullable=False))
    op.add_column('jobs', sa.Column('lease_expires_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('finished_at', sa.DateTime(), nullable=True))
    op.add_column('maintenance_tasks', sa.Column('fixed_start', sa.Integer(), nullable=True))
    op.add_column('maintenance_tasks', sa.Column('predecessors', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('maintenance_tasks', sa.Column('grouping_key', sa.String(length=64), nullable=True))
    op.add_column('plans', sa.Column('input_snapshot', sa.JSON(), server_default='{}', nullable=False))
    op.add_column('plans', sa.Column('objective', sa.Double(), nullable=True))
    op.add_column('plans', sa.Column('best_bound', sa.Double(), nullable=True))
    op.add_column('plans', sa.Column('parent_id', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=240), nullable=True))
    op.add_column('users', sa.Column('disabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('failed_logins', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_logins')
    op.drop_column('users', 'disabled')
    op.drop_column('users', 'password_hash')
    op.drop_column('plans', 'parent_id')
    op.drop_column('plans', 'best_bound')
    op.drop_column('plans', 'objective')
    op.drop_column('plans', 'input_snapshot')
    op.drop_column('maintenance_tasks', 'grouping_key')
    op.drop_column('maintenance_tasks', 'predecessors')
    op.drop_column('maintenance_tasks', 'fixed_start')
    op.drop_column('jobs', 'finished_at')
    op.drop_column('jobs', 'started_at')
    op.drop_column('jobs', 'lease_expires_at')
    op.drop_column('jobs', 'owner')
    op.drop_column('assessments', 'cutoff_cycle')
    op.drop_column('assessments', 'evidence')
    op.drop_index(op.f('ix_work_records_task_id'), table_name='work_records')
    op.drop_index(op.f('ix_work_records_plan_id'), table_name='work_records')
    op.drop_table('work_records')
    op.drop_index(op.f('ix_import_records_component_id'), table_name='import_records')
    op.drop_table('import_records')
    op.drop_index(op.f('ix_login_sessions_user_id'), table_name='login_sessions')
    op.drop_table('login_sessions')
    op.drop_table('model_registrations')
    op.drop_table('command_records')
    # ### end Alembic commands ###
