"""record expected part arrivals and receipts

Revision ID: c2ceb7b6aa9b
Revises: eab4b05e021f
Create Date: 2026-10-04 15:29:34.247728
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c2ceb7b6aa9b'
down_revision: Union[str, Sequence[str], None] = 'eab4b05e021f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part_arrivals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('part_id', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('arrival_slot', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_arrivals_part_id'), 'part_arrivals', ['part_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_part_arrivals_part_id'), table_name='part_arrivals')
    op.drop_table('part_arrivals')
    # ### end Alembic commands ###
