"""fleet recorded closures

Revision ID: e11b31b6122f
Revises: 61a3e0ef5591
Create Date: 2026-10-06 16:42:35.750544
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e11b31b6122f'
down_revision: Union[str, Sequence[str], None] = '61a3e0ef5591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fleet_recorded_closures',
    sa.Column('work_order_id', sa.String(length=64), nullable=False),
    sa.Column('aircraft', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('work_order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fleet_recorded_closures')
    # ### end Alembic commands ###
