"""retain durable job attempt history

Revision ID: eab4b05e021f
Revises: 64c201993bc1
Create Date: 2026-10-04 15:12:17.911647
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eab4b05e021f'
down_revision: Union[str, Sequence[str], None] = '64c201993bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_attempts',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=240), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_code', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'number', name='uq_job_attempt_number')
    )
    op.create_index(op.f('ix_job_attempts_job_id'), 'job_attempts', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_attempts_job_id'), table_name='job_attempts')
    op.drop_table('job_attempts')
    # ### end Alembic commands ###
