"""episode provenance and simulation ordering

Revision ID: f537880a4c71
Revises: f9261f3e5516
Create Date: 2026-10-04 22:12:45.496642
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f537880a4c71'
down_revision: Union[str, Sequence[str], None] = 'f9261f3e5516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('episode_id', sa.String(length=64), nullable=True))
    op.add_column('alerts', sa.Column('policy_context', sa.JSON(), server_default='{}', nullable=False))
    op.add_column('simulation_runs', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_runs', 'created_at')
    op.drop_column('alerts', 'policy_context')
    op.drop_column('alerts', 'episode_id')
    # ### end Alembic commands ###
