"""qualified resources and exclusive slot bookings

Revision ID: f9261f3e5516
Revises: c2ceb7b6aa9b
Create Date: 2026-10-04 21:55:48.152685
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f9261f3e5516'
down_revision: Union[str, Sequence[str], None] = 'c2ceb7b6aa9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alembic does not detect new CHECKs on existing PostgreSQL tables.
    op.create_check_constraint('ck_part_nonnegative_stock', 'parts', 'on_hand >= 0')
    op.create_check_constraint('ck_reservation_nonnegative', 'reservations', 'quantity >= 0')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_resources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('available', sa.JSON(), nullable=False),
    sa.Column('aircraft_ids', sa.JSON(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('scope_component_id', sa.String(length=64), nullable=True),
    sa.CheckConstraint("kind IN ('crew', 'bay')", name='ck_resource_kind'),
    sa.CheckConstraint('capacity > 0', name='ck_resource_capacity'),
    sa.CheckConstraint('valid_until > valid_from', name='ck_resource_validity'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_bookings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('unit', sa.Integer(), nullable=False),
    sa.Column('start_slot', sa.Integer(), nullable=False),
    sa.Column('end_slot', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.CheckConstraint('end_slot > start_slot', name='ck_booking_interval'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['maintenance_resources.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['maintenance_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'task_id', 'resource_id', name='uq_resource_booking')
    )
    op.create_table('resource_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('booking_id', sa.String(length=64), nullable=False),
    sa.Column('unit', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.CheckConstraint('unit >= 0 AND slot >= 0', name='ck_resource_slot_positive'),
    sa.ForeignKeyConstraint(['booking_id'], ['resource_bookings.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['maintenance_resources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'unit', 'slot', name='uq_resource_unit_slot')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint('ck_reservation_nonnegative', 'reservations', type_='check')
    op.drop_constraint('ck_part_nonnegative_stock', 'parts', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_slots')
    op.drop_table('resource_bookings')
    op.drop_table('maintenance_resources')
    # ### end Alembic commands ###
