import { lazy, Suspense } from "react";
import { useQuery, useQueries } from "@tanstack/react-query";
import { Link, useSearchParams } from "react-router-dom";
import { api, arrayOf, isComponentDetail, isFleetItem, isMaintenanceContext, isAlert, type Alert, type ComponentDetail, type FleetItem } from "../../shared/api/client";
import { AsyncState } from "../../shared/ui/AsyncState";
import { useSession } from "../access/SessionGate";
import { AssessmentSummary } from "../health/AssessmentSummary";
import { StatusBadge } from "../../shared/ui/StatusBadge";
import { Icon } from "../../shared/ui/Icon";
const AircraftScene = lazy(()=>import("./AircraftScene").then(module=>({default:module.AircraftScene})));
export function InspectionPage() {
  const session=useSession();
  const [params,setParams]=useSearchParams();
  const fleet=useQuery({queryKey:["fleet"],queryFn:()=>api<FleetItem[]>("/fleet",undefined,arrayOf(isFleetItem))});
  const aircraft=fleet.data?.find(item=>item.id===params.get("aircraft")) ?? fleet.data?.[0];
  const selected=aircraft?.component_ids.includes(params.get("component") ?? "") ? params.get("component") : aircraft?.component_ids[0] ?? null;
  const detail=useQuery({queryKey:["component",selected],queryFn:()=>api<ComponentDetail>(`/components/${encodeURIComponent(selected!)}`,undefined,isComponentDetail),enabled:!!selected});
  const componentRecords=useQueries({queries:(aircraft?.component_ids??[]).map(id=>({queryKey:["component",id],queryFn:()=>api<ComponentDetail>(`/components/${encodeURIComponent(id)}`,undefined,isComponentDetail)}))});
  const mapped=componentRecords.flatMap(record=>record.data&&record.data.aircraft_id===aircraft?.id&&record.data.kind==='engine'?[{id:record.data.id,label:`Engine · ${record.data.serial_number}`}]:[]);
  const choose=(id:string)=>{if(aircraft?.component_ids.includes(id))setParams({aircraft:aircraft.id,component:id});};
  const maintenance=useQuery({queryKey:['component-maintenance',selected],queryFn:()=>api(`/components/${encodeURIComponent(selected!)}/maintenance`,undefined,isMaintenanceContext),enabled:!!selected});
  const alerts=useQuery({queryKey:['alerts'],queryFn:()=>api<Alert[]>('/alerts',undefined,arrayOf(isAlert))});
  const recordedAlerts=alerts.data?.filter(item=>item.component_id===selected);
  const taskContext=maintenance.data?.component_id===selected?maintenance.data:undefined;
  const openTasks=taskContext?.tasks.filter(task=>task.status==='open');
  const canPlan=['planner','supervisor'].includes(session?.role??'');
  const assessment=detail.data?.assessment;

  return <section className="inspection-page"><div className="inspection-heading"><div><span className="eyebrow">SPATIAL CONTEXT. TRACEABLE DECISIONS.</span><h1>Aircraft inspection<span className="heading-dot">.</span></h1><p>Select an aircraft and inspect the evidence behind its next maintenance decision.</p></div><Link className="button-secondary" to="/fleet/register"><Icon name="grid" size={16}/>Aircraft register</Link></div>
    <AsyncState loading={fleet.isLoading} error={fleet.error} empty={!fleet.data?.length} emptyMessage="No aircraft records yet" onRetry={()=>void fleet.refetch()}>
      <div className="inspection-workspace"><aside className="aircraft-picker"><span className="eyebrow">YOUR FLEET</span><h2>Aircraft</h2>{fleet.data?.map(item=><button className={`aircraft-choice ${item.id===aircraft?.id?'selected':''}`} key={item.id} aria-pressed={item.id===aircraft?.id} onClick={()=>setParams({aircraft:item.id,...(item.component_ids[0]?{component:item.component_ids[0]}:{})})}><Icon name="aircraft" size={26}/><span><strong>{item.tail_number}</strong><small>{item.components} mapped component{item.components===1?'':'s'}</small></span><span className="aircraft-choice-work">{item.open_tasks} open</span></button>)}<p className="footnote">Fleet mappings and logistics are synthetic demonstrator records.</p></aside>
        <article className="inspection-model"><header><div><span className="eyebrow">SELECTED AIRCRAFT</span><h2>{aircraft?.tail_number}</h2><p>{aircraft?.label}</p></div><span className="source-tag">{aircraft?.provenance}</span></header><Suspense fallback={<div className="scene-loading" role="status">Loading aircraft view…</div>}><AircraftScene components={mapped} selected={selected} onSelect={choose}/></Suspense>{componentRecords.some(record=>record.isLoading)&&<p role="status">Loading installation identities…</p>}{!mapped.length&&!componentRecords.some(record=>record.isLoading)&&<p className="empty-state">No verified engine mappings returned. No installation is inferred.</p>}</article>
        <aside className="inspection-evidence"><div className="inspection-panel-heading"><span className="eyebrow">COMPONENT EVIDENCE</span><span className="panel-index">01 / REVIEW</span></div><AsyncState loading={detail.isLoading} error={detail.error} empty={!selected} emptyMessage="Select a mapped component" onRetry={()=>void detail.refetch()}>{detail.data&&detail.data.id===selected&&detail.data.aircraft_id===aircraft?.id&&<><h2>{detail.data.serial_number}</h2><p className="component-kind">{detail.data.kind} · Recorded cycle {detail.data.current_cycle}</p><StatusBadge status={assessment?.state??"unavailable"}/><AssessmentSummary assessment={assessment}/><Link className="button" to={`/components/${encodeURIComponent(selected!)}`}>Inspect history & evidence<Icon name="arrow" size={16}/></Link><div className="inspection-quality"><h3>Data quality</h3>{assessment?.quality_findings.length?assessment.quality_findings.map(finding=><p key={finding.code}><Icon name="warning" size={15}/>{finding.message}</p>):<p>{assessment?'No quality findings recorded.':'Assessment eligibility has not been established.'}</p>}</div><div className="inspection-constraints"><h3>Maintenance & constraints</h3>{maintenance.isLoading?<p role="status">Loading task context…</p>:maintenance.data&&!taskContext?<p role="alert">Task context does not match the selected component.</p>:maintenance.error?<p role="alert">Task context unavailable. <button className="text-button" onClick={()=>void maintenance.refetch()}>Retry</button></p>:<><p>{openTasks?.length??0} open component tasks · Mandatory work is separate from prediction state.</p>{openTasks?.slice(0,2).map(task=><p key={task.id}><strong>{task.title}</strong><br/>{task.mandatory?'Mandatory':'Optional'} · Deadline hour {task.deadline_slot*(maintenance.data?.slot_duration_hours??8)} · Skill: {task.required_skill}{task.part_id&&<><br/>{task.part_id}: {task.part_required} needed, {task.part_available??'unknown'} available</>}</p>)}</>}{recordedAlerts?.[0]&&<p>Recorded attention: {recordedAlerts[0].reason}</p>}</div>{canPlan?<Link className="inspection-next" to={`/planning?aircraft=${encodeURIComponent(aircraft!.id)}&component=${encodeURIComponent(selected!)}`}>{openTasks?.length?'Plan maintenance':'Review saved plans'}<Icon name="arrow" size={16}/></Link>:<p className="footnote">Planning requires planner or supervisor permission. Evidence remains available.</p>}<details className="technical-details"><summary>Assessment provenance</summary><dl><dt>Input version</dt><dd className="mono">{assessment?.input_version??"No assessment"}</dd><dt>Model</dt><dd>{assessment?.model_version??"Unavailable"}</dd><dt>Component identity</dt><dd className="mono">{detail.data.id}</dd></dl></details></>}{detail.data&&(detail.data.id!==selected||detail.data.aircraft_id!==aircraft?.id)&&<p role="alert">Returned component does not match the selected aircraft. Refresh before use.</p>}</AsyncState></aside>
      </div><div className="inspection-recent"><h2>Recent component records</h2>{alerts.isError?<p>Alert history is unavailable.</p>:recordedAlerts?.length?<ul>{recordedAlerts.slice(0,3).map(alert=><li key={alert.id}><StatusBadge status={alert.state}/><span>{alert.reason}</span><small>Policy {alert.policy_version} · {alert.id}</small></li>)}</ul>:<p>No alert records returned for this component.</p>}</div><div className="inspection-journey"><span className="eyebrow">THE DECISION PATH</span><Link to={selected?`/components/${encodeURIComponent(selected)}`:'/fleet/register'}><span>01</span>Inspect evidence<Icon name="arrow" size={16}/></Link><Link to="/planning"><span>02</span>Review a proposal<Icon name="arrow" size={16}/></Link><Link to="/inventory"><span>03</span>Check part arrivals<Icon name="arrow" size={16}/></Link><Link to="/scenarios"><span>04</span>Compare projections<Icon name="arrow" size={16}/></Link></div>
    </AsyncState>
  </section>;
}
